# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iosFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for iosFlutter
  
  #切换路径时需重新pod install
  flutter_application_path = '../myflutter/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
